namespace GuitarConfiguratorSharp.NetCore.Configuration.PS2;

public enum Ps2Axis
{
    GunconHSync,
    GunconVSync,
    MouseX,
    MouseY,
    NegConTwist,
    NegConTwistI,
    NegConTwistIi,
    NegConTwistL,
    JogConWheel,
    GuitarWhammy,
    DualshockLeftX,
    DualshockLeftY,
    DualshockRightX,
    DualshockRightY,
    Dualshock2LeftX,
    Dualshock2LeftY,
    Dualshock2RightX,
    Dualshock2RightY,
    Dualshock2L1,
    Dualshock2R1,
    Dualshock2RightButton,
    Dualshock2LeftButton,
    Dualshock2UpButton,
    Dualshock2DownButton,
    Dualshock2Triangle,
    Dualshock2Circle,
    Dualshock2Cross,
    Dualshock2Square,
    Dualshock2L2,
    Dualshock2R2
}