namespace GuitarConfiguratorSharp.NetCore.Configuration.Wii;

public enum WiiButtonType
{
    GuitarGreen,
    GuitarRed,
    GuitarYellow,
    GuitarBlue,
    GuitarOrange,
    GuitarMinus,
    GuitarPlus,
    GuitarStrumUp,
    GuitarStrumDown,
    DrumGreen,
    DrumRed,
    DrumYellow,
    DrumBlue,
    DrumOrange,
    DrumMinus,
    DrumPlus,
    DrumKickPedal,
    DrumHiHatPedal,
    NunchukC,
    NunchukZ,
    UDrawPenClick,
    UDrawPenButton1,
    UDrawPenButton2,
    TaTaConLeftDrumRim,
    TaTaConLeftDrumCenter,
    TaTaConRightDrumRim,
    TaTaConRightDrumCenter,
    DjHeroEuphoria,
    DjHeroLeftGreen,
    DjHeroLeftRed,
    DjHeroLeftBlue,
    DjHeroRightGreen,
    DjHeroRightRed,
    DjHeroRightBlue,
    DjHeroMinus,
    DjHeroPlus,
    ClassicA,
    ClassicB,
    ClassicX,
    ClassicY,
    ClassicDPadUp,
    ClassicDPadDown,
    ClassicDPadLeft,
    ClassicDPadRight,
    ClassicZl,
    ClassicZr,
    ClassicLt,
    ClassicRt,
    ClassicPlus,
    ClassicMinus,
    ClassicHome


}